kind: pipeline
name: docker-push
steps:
- name: docker
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    repo: grafana/kubernetes-diff-logger
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
trigger:
  ref:
    include:
    - refs/tags/v*